"""Local Markdown + SQLite storage for the NanoBot LLM Wiki."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sqlite3
import tempfile
import threading
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from nanobot_llm_wiki.paths import default_workspace, expand_path

BRIDGE_START = "<!-- nanobot-llm-wiki:start -->"
BRIDGE_END = "<!-- nanobot-llm-wiki:end -->"
SKILL_MARKER = "<!-- Generated by nanobot-llm-wiki. Safe to update. -->"
IMPORT_EXTENSIONS = {
    ".adoc",
    ".csv",
    ".json",
    ".jsonl",
    ".md",
    ".markdown",
    ".rst",
    ".toml",
    ".txt",
    ".yaml",
    ".yml",
}
_LINK_SOURCE_LOCK = threading.RLock()


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", value).strip().lower()
    chars: list[str] = []
    previous_dash = False
    for char in normalized:
        if char.isalnum():
            chars.append(char)
            previous_dash = False
        elif char in {" ", "-", "_", ".", "/", "\\", ":"} and not previous_dash:
            chars.append("-")
            previous_dash = True
    slug = "".join(chars).strip("-")
    return slug or "page"


def _json_list(value: Iterable[Any]) -> str:
    return json.dumps([item for item in value], ensure_ascii=False)


def _load_json_list(value: str | None) -> list[Any]:
    if not value:
        return []
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return []
    return parsed if isinstance(parsed, list) else []


def _short_hash(value: str, *, length: int = 10) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:length]


def _frontmatter_value(value: Any) -> str:
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


@dataclass(slots=True)
class WikiPage:
    id: str
    title: str
    content: str
    page_type: str = "note"
    tags: list[str] = field(default_factory=list)
    aliases: list[str] = field(default_factory=list)
    confidence: float = 0.7
    created_at: str = field(default_factory=utc_now)
    updated_at: str = field(default_factory=utc_now)
    source_cursors: list[int] = field(default_factory=list)

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "WikiPage":
        return cls(
            id=row["id"],
            title=row["title"],
            content=row["content"],
            page_type=row["page_type"],
            tags=[str(item) for item in _load_json_list(row["tags_json"])],
            aliases=[str(item) for item in _load_json_list(row["aliases_json"])],
            confidence=float(row["confidence"]),
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            source_cursors=[int(item) for item in _load_json_list(row["source_cursors_json"])],
        )

    def to_markdown(self) -> str:
        meta = {
            "id": self.id,
            "title": self.title,
            "type": self.page_type,
            "tags": self.tags,
            "aliases": self.aliases,
            "confidence": self.confidence,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "source_cursors": self.source_cursors,
        }
        lines = ["---"]
        lines.extend(f"{key}: {_frontmatter_value(value)}" for key, value in meta.items())
        lines.extend(["---", "", self.content.strip(), ""])
        return "\n".join(lines)


@dataclass(slots=True)
class SearchResult:
    page: WikiPage
    score: float = 0.0


@dataclass(slots=True)
class WikiLink:
    from_id: str
    from_title: str
    to_id: str
    to_title: str
    relation: str
    created_at: str


@dataclass(slots=True)
class KnowledgeImportItem:
    path: str
    page: WikiPage


@dataclass(slots=True)
class KnowledgeImportResult:
    raw_path: str
    index_page: WikiPage
    imported: list[KnowledgeImportItem] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)

    @property
    def source_path(self) -> str:
        return self.raw_path


class WikiStore:
    """A local Wiki store scoped to a NanoBot workspace."""

    def __init__(self, workspace: str | Path | None = None, *, create: bool = True):
        self.workspace = expand_path(workspace) if workspace else default_workspace()
        self.wiki_dir = self.workspace / "memory" / "wiki"
        self.pages_dir = self.wiki_dir / "pages"
        self.archive_dir = self.wiki_dir / "archive"
        self.db_path = self.wiki_dir / "wiki.db"
        self.links_path = self.wiki_dir / "links.jsonl"
        self.cursor_path = self.wiki_dir / ".cursor"
        if create:
            self.init()

    def init(self) -> None:
        self.pages_dir.mkdir(parents=True, exist_ok=True)
        self.archive_dir.mkdir(parents=True, exist_ok=True)
        with self._connect() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS pages (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    page_type TEXT NOT NULL,
                    tags_json TEXT NOT NULL,
                    aliases_json TEXT NOT NULL,
                    confidence REAL NOT NULL,
                    content TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    source_cursors_json TEXT NOT NULL
                )
                """
            )
            conn.execute("CREATE INDEX IF NOT EXISTS idx_pages_title ON pages(title)")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS links (
                    from_id TEXT NOT NULL,
                    to_id TEXT NOT NULL,
                    relation TEXT NOT NULL DEFAULT 'related',
                    created_at TEXT NOT NULL,
                    PRIMARY KEY (from_id, to_id, relation)
                )
                """
            )
            try:
                conn.execute(
                    """
                    CREATE VIRTUAL TABLE IF NOT EXISTS page_fts
                    USING fts5(page_id UNINDEXED, title, content, tags)
                    """
                )
            except sqlite3.Error:
                conn.execute(
                    """
                    CREATE TABLE IF NOT EXISTS page_fts (
                        page_id TEXT PRIMARY KEY,
                        title TEXT NOT NULL,
                        content TEXT NOT NULL,
                        tags TEXT NOT NULL
                    )
                    """
                )
        self._initialize_link_source()

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    @staticmethod
    def _link_key(record: dict[str, str]) -> tuple[str, str, str]:
        return record["from_id"], record["to_id"], record["relation"]

    def _read_link_source(self) -> tuple[list[dict[str, str]], list[str]]:
        records: list[dict[str, str]] = []
        skipped: list[str] = []
        seen: set[tuple[str, str, str]] = set()
        try:
            lines = self.links_path.read_text(encoding="utf-8").splitlines()
        except FileNotFoundError:
            return records, skipped
        except OSError as exc:
            return records, [f"{self.links_path.name}: {exc}"]

        for line_number, line in enumerate(lines, start=1):
            if not line.strip():
                continue
            try:
                raw = json.loads(line)
            except json.JSONDecodeError as exc:
                skipped.append(f"{self.links_path.name} line {line_number}: {exc.msg}")
                continue
            if not isinstance(raw, dict):
                skipped.append(f"{self.links_path.name} line {line_number}: expected an object")
                continue
            record = {
                "from_id": str(raw.get("from_id") or "").strip(),
                "to_id": str(raw.get("to_id") or "").strip(),
                "relation": str(raw.get("relation") or "related").strip() or "related",
                "created_at": str(raw.get("created_at") or "").strip(),
            }
            if not record["from_id"] or not record["to_id"] or not record["created_at"]:
                skipped.append(
                    f"{self.links_path.name} line {line_number}: "
                    "from_id, to_id, and created_at are required"
                )
                continue
            key = self._link_key(record)
            if key in seen:
                continue
            seen.add(key)
            records.append(record)
        return records, skipped

    def _write_link_source(self, records: list[dict[str, str]]) -> None:
        self.links_path.parent.mkdir(parents=True, exist_ok=True)
        text = "".join(
            f"{json.dumps(record, ensure_ascii=False, sort_keys=True)}\n"
            for record in records
        )
        temporary_path: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                dir=self.links_path.parent,
                prefix=f".{self.links_path.name}.",
                suffix=".tmp",
                delete=False,
            ) as handle:
                handle.write(text)
                temporary_path = Path(handle.name)
            temporary_path.replace(self.links_path)
        finally:
            if temporary_path is not None and temporary_path.exists():
                temporary_path.unlink()

    def _database_link_records(self) -> list[dict[str, str]]:
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT from_id, to_id, relation, created_at
                FROM links
                ORDER BY created_at ASC, from_id ASC, to_id ASC, relation ASC
                """
            ).fetchall()
        return [
            {
                "from_id": str(row["from_id"]),
                "to_id": str(row["to_id"]),
                "relation": str(row["relation"]),
                "created_at": str(row["created_at"]),
            }
            for row in rows
        ]

    def _initialize_link_source(self) -> None:
        with _LINK_SOURCE_LOCK:
            if not self.links_path.exists():
                self._write_link_source(self._database_link_records())
                return
            records, skipped = self._read_link_source()
            if not skipped:
                self._replace_link_index(records)

    def _replace_link_index(self, records: list[dict[str, str]]) -> tuple[int, list[str]]:
        indexed = 0
        deferred: list[str] = []
        with self._connect() as conn:
            page_ids = {
                str(row["id"])
                for row in conn.execute("SELECT id FROM pages").fetchall()
            }
            conn.execute("DELETE FROM links")
            for record in records:
                if record["from_id"] not in page_ids or record["to_id"] not in page_ids:
                    deferred.append(
                        f"{record['from_id']} -> {record['to_id']}: page is not active"
                    )
                    continue
                conn.execute(
                    """
                    INSERT OR IGNORE INTO links(from_id, to_id, relation, created_at)
                    VALUES (?, ?, ?, ?)
                    """,
                    (
                        record["from_id"],
                        record["to_id"],
                        record["relation"],
                        record["created_at"],
                    ),
                )
                indexed += 1
        return indexed, deferred

    def _remove_link_source_records_for_page(self, page_id: str) -> int:
        with _LINK_SOURCE_LOCK:
            records, skipped = self._read_link_source()
            if skipped:
                raise ValueError("cannot update links.jsonl: " + "; ".join(skipped))
            retained = [
                record
                for record in records
                if record["from_id"] != page_id and record["to_id"] != page_id
            ]
            removed = len(records) - len(retained)
            if removed:
                self._write_link_source(retained)
            return removed

    def page_path(self, page_id: str) -> Path:
        return self.pages_dir / f"{page_id}.md"

    def get_cursor(self) -> int:
        try:
            return int(self.cursor_path.read_text(encoding="utf-8").strip())
        except (FileNotFoundError, ValueError):
            return 0

    def set_cursor(self, cursor: int) -> None:
        self.cursor_path.parent.mkdir(parents=True, exist_ok=True)
        self.cursor_path.write_text(str(cursor), encoding="utf-8")

    def _row_to_page(self, row: sqlite3.Row | None) -> WikiPage | None:
        return WikiPage.from_row(row) if row is not None else None

    def _get_page_by_id(self, page_id: str) -> WikiPage | None:
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM pages WHERE id = ?", (page_id,)).fetchone()
        return self._row_to_page(row)

    def _get_page_by_title(self, title: str) -> WikiPage | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM pages WHERE lower(title) = lower(?)",
                (title,),
            ).fetchone()
        return self._row_to_page(row)

    def get_page(self, selector: str) -> WikiPage | None:
        selector = selector.strip()
        if not selector:
            return None
        exact_id = self._get_page_by_id(selector)
        if exact_id:
            return exact_id
        exact_title = self._get_page_by_title(selector)
        if exact_title:
            return exact_title
        normalized_id = slugify(selector)
        if normalized_id != selector:
            normalized_page = self._get_page_by_id(normalized_id)
            if normalized_page:
                return normalized_page
        with self._connect() as conn:
            rows = conn.execute("SELECT * FROM pages").fetchall()
        lowered = selector.casefold()
        for row in rows:
            page = WikiPage.from_row(row)
            if any(alias.casefold() == lowered for alias in page.aliases):
                return page
        return None

    def list_pages(self, *, limit: int = 50) -> list[WikiPage]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM pages ORDER BY updated_at DESC LIMIT ?",
                (max(1, limit),),
            ).fetchall()
        return [WikiPage.from_row(row) for row in rows]

    def upsert_page(
        self,
        *,
        title: str,
        content: str,
        page_type: str = "note",
        tags: list[str] | None = None,
        aliases: list[str] | None = None,
        confidence: float = 0.7,
        source_cursors: list[int] | None = None,
        page_id: str | None = None,
        mode: str = "replace",
    ) -> WikiPage:
        if not title.strip():
            raise ValueError("title is required")
        if mode not in {"replace", "append"}:
            raise ValueError("mode must be 'replace' or 'append'")

        if page_id:
            resolved_id = slugify(page_id)
            existing = self._get_page_by_id(resolved_id)
        else:
            existing = self._get_page_by_title(title.strip())
            resolved_id = existing.id if existing else self._available_page_id(title)
        now = utc_now()
        resolved_content = content.strip()
        if existing and mode == "append":
            resolved_content = self._append_content(existing.content, resolved_content)

        page = WikiPage(
            id=resolved_id,
            title=title.strip() or (existing.title if existing else resolved_id),
            content=resolved_content,
            page_type=(page_type or (existing.page_type if existing else "note")).strip(),
            tags=self._merged_strings(existing.tags if existing else [], tags or []),
            aliases=self._merged_strings(existing.aliases if existing else [], aliases or []),
            confidence=max(0.0, min(1.0, float(confidence))),
            created_at=existing.created_at if existing else now,
            updated_at=now,
            source_cursors=self._merged_ints(
                existing.source_cursors if existing else [],
                source_cursors or [],
            ),
        )
        self._save_page(page)
        return page

    def _available_page_id(self, title: str) -> str:
        base = slugify(title)
        if self._get_page_by_id(base) is None:
            return base
        digest = _short_hash(title.strip().casefold(), length=8)
        candidate = f"{base}-{digest}"
        suffix = 2
        while self._get_page_by_id(candidate) is not None:
            candidate = f"{base}-{digest}-{suffix}"
            suffix += 1
        return candidate

    @staticmethod
    def _append_content(existing: str, addition: str) -> str:
        existing = existing.rstrip()
        addition = addition.strip()
        if not addition:
            return existing
        if addition in existing:
            return existing
        return f"{existing}\n\n{addition}" if existing else addition

    @staticmethod
    def _merged_strings(left: list[str], right: list[str]) -> list[str]:
        seen: set[str] = set()
        merged: list[str] = []
        for item in [*left, *right]:
            clean = str(item).strip()
            key = clean.casefold()
            if clean and key not in seen:
                seen.add(key)
                merged.append(clean)
        return merged

    @staticmethod
    def _merged_ints(left: list[int], right: list[int]) -> list[int]:
        values = {int(item) for item in [*left, *right] if str(item).strip()}
        return sorted(values)

    def import_knowledge_base(
        self,
        raw: str | Path | None = None,
        *,
        source: str | Path | None = None,
        index_title: str | None = None,
        tags: list[str] | None = None,
        page_type: str = "knowledge-doc",
        relation: str = "contains",
        max_bytes: int = 512_000,
    ) -> KnowledgeImportResult:
        if raw is None:
            raw = source
        elif source is not None and Path(raw).expanduser().resolve() != Path(source).expanduser().resolve():
            raise ValueError("raw and source must refer to the same path")
        if raw is None:
            raise ValueError("raw path is required")

        raw_path = Path(raw).expanduser().resolve()
        if not raw_path.exists():
            raise FileNotFoundError(f"raw knowledge base path not found: {raw_path}")
        if max_bytes < 1:
            raise ValueError("max_bytes must be greater than 0")

        files = self._import_files(raw_path)
        kb_slug = slugify(raw_path.stem if raw_path.is_file() else raw_path.name)
        title = index_title or f"Imported Knowledge Base: {raw_path.name}"
        base_tags = self._merged_strings(["knowledge-base", "imported", kb_slug], tags or [])
        index_id = f"kb-{kb_slug}-{_short_hash(str(raw_path))}"
        index_page = self.upsert_page(
            title=title,
            content=self._knowledge_index_content(raw_path, []),
            page_type="knowledge-base-index",
            tags=base_tags,
            aliases=[raw_path.name, str(raw_path)],
            page_id=index_id,
            mode="replace",
        )

        imported: list[KnowledgeImportItem] = []
        skipped: list[str] = []
        for path in files:
            reason = self._skip_import_file(path, max_bytes=max_bytes)
            rel_path = self._relative_import_path(raw_path, path)
            if reason:
                skipped.append(f"{rel_path}: {reason}")
                continue
            try:
                raw = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                skipped.append(f"{rel_path}: not valid UTF-8 text")
                continue
            except OSError as exc:
                skipped.append(f"{rel_path}: {exc}")
                continue

            page = self.upsert_page(
                title=self._title_from_import(path, rel_path, raw),
                content=self._import_page_content(rel_path, raw),
                page_type=page_type,
                tags=self._merged_strings(base_tags, [path.suffix.lower().lstrip(".")]),
                aliases=[rel_path, path.name, path.stem],
                page_id=f"{index_id}-{slugify(rel_path)}",
                mode="replace",
            )
            self.link_pages(index_page.id, page.id, relation)
            imported.append(KnowledgeImportItem(path=rel_path, page=page))

        index_page = self.upsert_page(
            title=title,
            content=self._knowledge_index_content(raw_path, imported),
            page_type="knowledge-base-index",
            tags=base_tags,
            aliases=[raw_path.name, str(raw_path)],
            page_id=index_id,
            mode="replace",
        )
        self.write_memory_bridge()
        return KnowledgeImportResult(
            raw_path=str(raw_path),
            index_page=index_page,
            imported=imported,
            skipped=skipped,
        )

    @staticmethod
    def _import_files(raw_path: Path) -> list[Path]:
        if raw_path.is_file():
            return [raw_path]
        return sorted(path for path in raw_path.rglob("*") if path.is_file())

    @staticmethod
    def _relative_import_path(raw_path: Path, path: Path) -> str:
        root = raw_path.parent if raw_path.is_file() else raw_path
        try:
            return path.relative_to(root).as_posix()
        except ValueError:
            return path.name

    @staticmethod
    def _skip_import_file(path: Path, *, max_bytes: int) -> str | None:
        if path.name.startswith("."):
            return "hidden file"
        if path.suffix.lower() not in IMPORT_EXTENSIONS:
            return f"unsupported extension {path.suffix or '(none)'}"
        size = path.stat().st_size
        if size > max_bytes:
            return f"file is larger than {max_bytes} bytes"
        return None

    @staticmethod
    def _title_from_import(path: Path, rel_path: str, content: str) -> str:
        for line in content.splitlines()[:40]:
            match = re.match(r"^\s{0,3}#\s+(.+?)\s*$", line)
            if match:
                return match.group(1).strip()
        stem = Path(rel_path).with_suffix("").as_posix()
        return stem.replace("/", " / ") or path.stem

    @staticmethod
    def _import_page_content(rel_path: str, content: str) -> str:
        body = content.strip()
        return f"## Raw\n\n- Raw path: `{rel_path}`\n\n## Content\n\n{body}"

    @staticmethod
    def _knowledge_index_content(
        raw_path: Path,
        imported: list[KnowledgeImportItem],
    ) -> str:
        lines = [
            "## Imported Knowledge Base",
            "",
            f"- Raw root: `{raw_path}`",
            f"- Imported pages: {len(imported)}",
            "",
            "## Pages",
            "",
        ]
        if not imported:
            lines.append("- No pages imported yet.")
        else:
            lines.extend(
                f"- [[{item.page.title}]] (`{item.page.id}`) from `{item.path}`"
                for item in imported
            )
        return "\n".join(lines)

    def _save_page(self, page: WikiPage) -> None:
        self.page_path(page.id).write_text(page.to_markdown(), encoding="utf-8")
        self._save_page_record(page)

    def _save_page_record(self, page: WikiPage) -> None:
        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO pages (
                    id, title, page_type, tags_json, aliases_json, confidence,
                    content, created_at, updated_at, source_cursors_json
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    title = excluded.title,
                    page_type = excluded.page_type,
                    tags_json = excluded.tags_json,
                    aliases_json = excluded.aliases_json,
                    confidence = excluded.confidence,
                    content = excluded.content,
                    updated_at = excluded.updated_at,
                    source_cursors_json = excluded.source_cursors_json
                """,
                (
                    page.id,
                    page.title,
                    page.page_type,
                    _json_list(page.tags),
                    _json_list(page.aliases),
                    page.confidence,
                    page.content,
                    page.created_at,
                    page.updated_at,
                    _json_list(page.source_cursors),
                ),
            )
            self._upsert_fts(conn, page)

    def reindex_from_disk(self) -> dict[str, Any]:
        """Rebuild SQLite search records from Markdown pages on disk."""
        indexed: list[str] = []
        skipped: list[str] = []
        file_ids: set[str] = set()
        for path in sorted(self.pages_dir.glob("*.md")):
            if path.name.startswith(".") or not path.is_file():
                continue
            try:
                page = self._page_from_markdown_path(path)
            except (OSError, ValueError) as exc:
                skipped.append(f"{path.name}: {exc}")
                continue
            self._save_page_record(page)
            file_ids.add(page.id)
            indexed.append(page.id)

        removed: list[str] = []
        with self._connect() as conn:
            rows = conn.execute("SELECT id FROM pages").fetchall()
        for row in rows:
            page_id = str(row["id"])
            if page_id in file_ids or self.page_path(page_id).exists():
                continue
            self._delete_page_record(page_id)
            removed.append(page_id)

        with _LINK_SOURCE_LOCK:
            link_records, link_source_skipped = self._read_link_source()
            links_indexed, deferred_links = self._replace_link_index(link_records)
        self.write_memory_bridge()
        return {
            "indexed": len(indexed),
            "removed": len(removed),
            "skipped": skipped,
            "page_ids": indexed,
            "removed_ids": removed,
            "links_indexed": links_indexed,
            "links_skipped": [*link_source_skipped, *deferred_links],
        }

    def _delete_page_record(self, page_id: str) -> None:
        with self._connect() as conn:
            conn.execute("DELETE FROM links WHERE from_id = ? OR to_id = ?", (page_id, page_id))
            conn.execute("DELETE FROM page_fts WHERE page_id = ?", (page_id,))
            conn.execute("DELETE FROM pages WHERE id = ?", (page_id,))

    def _page_from_markdown_path(self, path: Path) -> WikiPage:
        text = path.read_text(encoding="utf-8")
        meta, content = self._split_frontmatter(text)
        fallback_time = datetime.fromtimestamp(
            path.stat().st_mtime,
            timezone.utc,
        ).replace(microsecond=0).isoformat()
        frontmatter_id = str(meta.get("id") or "").strip()
        frontmatter_path = self.page_path(slugify(frontmatter_id)) if frontmatter_id else None
        page_id = slugify(frontmatter_id) if frontmatter_path == path else path.stem
        return WikiPage(
            id=page_id,
            title=str(meta.get("title") or self._title_from_markdown(content, page_id)).strip(),
            content=content.strip(),
            page_type=str(meta.get("type") or meta.get("page_type") or "note").strip() or "note",
            tags=self._frontmatter_list(meta.get("tags")),
            aliases=self._frontmatter_list(meta.get("aliases")),
            confidence=self._frontmatter_float(meta.get("confidence"), default=0.7),
            created_at=str(meta.get("created_at") or fallback_time),
            updated_at=str(meta.get("updated_at") or fallback_time),
            source_cursors=self._frontmatter_ints(meta.get("source_cursors")),
        )

    @staticmethod
    def _split_frontmatter(text: str) -> tuple[dict[str, str], str]:
        lines = text.splitlines()
        if not lines or lines[0].strip() != "---":
            return {}, text
        end_index = None
        for index, line in enumerate(lines[1:], start=1):
            if line.strip() == "---":
                end_index = index
                break
        if end_index is None:
            return {}, text
        meta: dict[str, str] = {}
        for line in lines[1:end_index]:
            if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
                continue
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
        return meta, "\n".join(lines[end_index + 1 :])

    @staticmethod
    def _frontmatter_list(value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, list):
            values = value
        else:
            raw = str(value).strip()
            values = _load_json_list(raw)
            if not values and raw and raw != "[]":
                values = [part.strip() for part in raw.split(",")]
        return [str(item).strip() for item in values if str(item).strip()]

    @staticmethod
    def _frontmatter_float(value: Any, *, default: float) -> float:
        try:
            return max(0.0, min(1.0, float(value)))
        except (TypeError, ValueError):
            return default

    @staticmethod
    def _frontmatter_ints(value: Any) -> list[int]:
        parsed: list[int] = []
        for item in WikiStore._frontmatter_list(value):
            try:
                parsed.append(int(item))
            except ValueError:
                continue
        return sorted(set(parsed))

    @staticmethod
    def _title_from_markdown(content: str, fallback_id: str) -> str:
        for line in content.splitlines()[:40]:
            match = re.match(r"^\s{0,3}#\s+(.+?)\s*$", line)
            if match:
                return match.group(1).strip()
        return fallback_id.replace("-", " ").strip().title() or fallback_id

    def _upsert_fts(self, conn: sqlite3.Connection, page: WikiPage) -> None:
        conn.execute("DELETE FROM page_fts WHERE page_id = ?", (page.id,))
        alias_text = " ".join(page.aliases)
        conn.execute(
            "INSERT INTO page_fts(page_id, title, content, tags) VALUES (?, ?, ?, ?)",
            (
                page.id,
                page.title,
                "\n".join(part for part in [page.content, alias_text] if part),
                " ".join([*page.tags, *page.aliases]),
            ),
        )

    def search(self, query: str, *, limit: int = 5, tag: str | None = None) -> list[SearchResult]:
        limit = max(1, min(int(limit), 25))
        query = query.strip()
        tag_filter = tag.casefold().strip() if tag else ""
        if not query:
            pages = self.list_pages(limit=limit)
            return [SearchResult(page=page, score=0.0) for page in self._filter_tag(pages, tag_filter)]

        candidates: list[SearchResult] = []
        exact_page = self.get_page(query)
        if exact_page:
            candidates.append(SearchResult(page=exact_page, score=-100.0))

        candidates.extend(self._like_search(query, limit * 4, score=0.25))
        terms = self._query_terms(query)
        try:
            candidates.extend(self._fts_search(self._to_fts_query(terms, operator="AND"), limit * 4))
            if self._should_expand_query(query, terms):
                candidates.extend(self._fts_search(self._to_fts_query(terms, operator="OR"), limit * 4))
        except sqlite3.Error:
            pass

        return self._merge_search_results(candidates, tag_filter=tag_filter)[:limit]

    @staticmethod
    def _query_terms(query: str) -> list[str]:
        terms = re.findall(r"[\w\u4e00-\u9fff]+", query, flags=re.UNICODE)
        return terms[:8]

    @staticmethod
    def _to_fts_query(terms: list[str], *, operator: str) -> str:
        if not terms:
            return ""
        joiner = f" {operator} "
        return joiner.join(json.dumps(term) for term in terms)

    @staticmethod
    def _should_expand_query(query: str, terms: list[str]) -> bool:
        if len(terms) < 2:
            return False
        if len(terms) > 3:
            return False
        if any(any(char.isdigit() for char in term) for term in terms):
            return False
        return re.search(r"[-_:/\\]", query) is None

    def _fts_search(self, fts_query: str, limit: int) -> list[SearchResult]:
        if not fts_query:
            return []
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT p.*, bm25(page_fts) AS score
                FROM page_fts
                JOIN pages p ON p.id = page_fts.page_id
                WHERE page_fts MATCH ?
                ORDER BY score
                LIMIT ?
                """,
                (fts_query, limit),
            ).fetchall()
        return [
            SearchResult(page=WikiPage.from_row(row), score=float(row["score"]))
            for row in rows
        ]

    def _merge_search_results(
        self,
        results: Iterable[SearchResult],
        *,
        tag_filter: str,
    ) -> list[SearchResult]:
        merged: dict[str, SearchResult] = {}
        for result in results:
            if not self._page_has_tag(result.page, tag_filter):
                continue
            existing = merged.get(result.page.id)
            if existing is None or result.score < existing.score:
                merged[result.page.id] = result
        return sorted(merged.values(), key=lambda result: result.score)

    def _like_search(self, query: str, limit: int, *, score: float = 1.0) -> list[SearchResult]:
        query = query.strip()
        if not query:
            return []
        pattern = f"%{query}%"
        terms = self._query_terms(query)
        term_clauses: list[str] = []
        values: list[Any] = [pattern, pattern, pattern, pattern]
        for term in terms:
            term_pattern = f"%{term}%"
            term_clauses.append("(title LIKE ? OR content LIKE ? OR tags_json LIKE ? OR aliases_json LIKE ?)")
            values.extend([term_pattern, term_pattern, term_pattern, term_pattern])
        where = "(title LIKE ? OR content LIKE ? OR tags_json LIKE ? OR aliases_json LIKE ?)"
        if term_clauses:
            where = f"({where}) OR ({' AND '.join(term_clauses)})"
        values.append(limit)
        with self._connect() as conn:
            rows = conn.execute(
                f"""
                SELECT * FROM pages
                WHERE {where}
                ORDER BY updated_at DESC
                LIMIT ?
                """,
                tuple(values),
            ).fetchall()
        return [SearchResult(page=WikiPage.from_row(row), score=score) for row in rows]

    @staticmethod
    def _filter_tag(pages: list[WikiPage], tag_filter: str) -> list[WikiPage]:
        return [page for page in pages if WikiStore._page_has_tag(page, tag_filter)]

    @staticmethod
    def _page_has_tag(page: WikiPage, tag_filter: str) -> bool:
        if not tag_filter:
            return True
        return any(tag.casefold() == tag_filter for tag in page.tags)

    def link_pages(
        self,
        from_selector: str,
        to_selector: str,
        relation: str = "related",
    ) -> tuple[WikiPage, WikiPage]:
        from_page = self.get_page(from_selector)
        to_page = self.get_page(to_selector)
        if not from_page:
            raise KeyError(f"page not found: {from_selector}")
        if not to_page:
            raise KeyError(f"page not found: {to_selector}")
        resolved_relation = relation.strip() or "related"
        with _LINK_SOURCE_LOCK:
            records, skipped = self._read_link_source()
            if skipped:
                raise ValueError("cannot update links.jsonl: " + "; ".join(skipped))
            key = (from_page.id, to_page.id, resolved_relation)
            existing = next(
                (record for record in records if self._link_key(record) == key),
                None,
            )
            if existing is None:
                existing = {
                    "from_id": from_page.id,
                    "to_id": to_page.id,
                    "relation": resolved_relation,
                    "created_at": utc_now(),
                }
                records.append(existing)
                self._write_link_source(records)
            with self._connect() as conn:
                conn.execute(
                    """
                    INSERT OR IGNORE INTO links(from_id, to_id, relation, created_at)
                    VALUES (?, ?, ?, ?)
                    """,
                    (
                        from_page.id,
                        to_page.id,
                        resolved_relation,
                        existing["created_at"],
                    ),
                )
        return from_page, to_page

    def unlink_pages(
        self,
        from_selector: str,
        to_selector: str,
        relation: str | None = None,
    ) -> tuple[WikiPage, WikiPage, int]:
        from_page = self.get_page(from_selector)
        to_page = self.get_page(to_selector)
        if not from_page:
            raise KeyError(f"page not found: {from_selector}")
        if not to_page:
            raise KeyError(f"page not found: {to_selector}")
        resolved_relation = relation.strip() or "related" if relation is not None else None
        with _LINK_SOURCE_LOCK:
            records, skipped = self._read_link_source()
            if skipped:
                raise ValueError("cannot update links.jsonl: " + "; ".join(skipped))

            def should_remove(record: dict[str, str]) -> bool:
                if record["from_id"] != from_page.id or record["to_id"] != to_page.id:
                    return False
                return resolved_relation is None or record["relation"] == resolved_relation

            retained = [record for record in records if not should_remove(record)]
            removed = len(records) - len(retained)
            if removed:
                self._write_link_source(retained)
            with self._connect() as conn:
                if resolved_relation is None:
                    conn.execute(
                        "DELETE FROM links WHERE from_id = ? AND to_id = ?",
                        (from_page.id, to_page.id),
                    )
                else:
                    conn.execute(
                        "DELETE FROM links WHERE from_id = ? AND to_id = ? AND relation = ?",
                        (from_page.id, to_page.id, resolved_relation),
                    )
        return from_page, to_page, removed

    def list_links(self) -> list[WikiLink]:
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT
                    links.from_id,
                    from_page.title AS from_title,
                    links.to_id,
                    to_page.title AS to_title,
                    links.relation,
                    links.created_at
                FROM links
                JOIN pages AS from_page ON from_page.id = links.from_id
                JOIN pages AS to_page ON to_page.id = links.to_id
                ORDER BY links.created_at ASC, links.from_id ASC, links.to_id ASC
                """
            ).fetchall()
        return [
            WikiLink(
                from_id=row["from_id"],
                from_title=row["from_title"],
                to_id=row["to_id"],
                to_title=row["to_title"],
                relation=row["relation"],
                created_at=row["created_at"],
            )
            for row in rows
        ]

    def graph(self, *, limit: int = 200) -> dict[str, Any]:
        pages = self.list_pages(limit=limit)
        visible_ids = {page.id for page in pages}
        links = [
            link
            for link in self.list_links()
            if link.from_id in visible_ids and link.to_id in visible_ids
        ]
        return {
            "nodes": [
                {
                    "id": page.id,
                    "title": page.title,
                    "page_type": page.page_type,
                    "tags": page.tags,
                    "updated_at": page.updated_at,
                }
                for page in pages
            ],
            "links": [
                {
                    "from_id": link.from_id,
                    "from_title": link.from_title,
                    "to_id": link.to_id,
                    "to_title": link.to_title,
                    "relation": link.relation,
                    "created_at": link.created_at,
                }
                for link in links
            ],
        }

    def forget_page(self, selector: str, *, archive: bool = True) -> WikiPage:
        page = self.get_page(selector)
        if not page:
            raise KeyError(f"page not found: {selector}")
        if not archive:
            self._remove_link_source_records_for_page(page.id)
        source_path = self.page_path(page.id)
        if source_path.exists():
            if archive:
                target = self.archive_dir / f"{page.id}-{datetime.now().strftime('%Y%m%d%H%M%S')}.md"
                shutil.move(str(source_path), target)
            else:
                source_path.unlink()
        self._delete_page_record(page.id)
        return page

    def status(self) -> dict[str, Any]:
        with self._connect() as conn:
            page_count = int(conn.execute("SELECT COUNT(*) FROM pages").fetchone()[0])
            link_count = int(conn.execute("SELECT COUNT(*) FROM links").fetchone()[0])
        return {
            "workspace": str(self.workspace),
            "wiki_dir": str(self.wiki_dir),
            "db_path": str(self.db_path),
            "links_path": str(self.links_path),
            "pages": page_count,
            "links": link_count,
            "cursor": self.get_cursor(),
        }

    def ingest_history(self, *, limit: int = 50) -> dict[str, Any]:
        """Deterministically import new history.jsonl entries into a Wiki inbox page."""
        history_path = self.workspace / "memory" / "history.jsonl"
        cursor = self.get_cursor()
        entries: list[dict[str, Any]] = []
        try:
            with history_path.open("r", encoding="utf-8") as handle:
                for line in handle:
                    if not line.strip():
                        continue
                    try:
                        record = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    record_cursor = record.get("cursor")
                    if isinstance(record_cursor, int) and record_cursor > cursor:
                        entries.append(record)
        except FileNotFoundError:
            return {"processed": 0, "cursor": cursor, "page_id": None}

        batch = entries[: max(1, limit)]
        if not batch:
            return {"processed": 0, "cursor": cursor, "page_id": None}

        imported_lines = [
            f"- [{entry.get('timestamp', '?')}] cursor {entry.get('cursor')}: "
            f"{self._compact_text(str(entry.get('content', '')), 700)}"
            for entry in batch
        ]
        date_label = datetime.now().strftime("%Y-%m-%d")
        content = f"## Imported {date_label}\n\n" + "\n".join(imported_lines)
        page = self.upsert_page(
            title="Conversation Inbox",
            content=content,
            page_type="inbox",
            tags=["history", "inbox"],
            source_cursors=[int(entry["cursor"]) for entry in batch],
            mode="append",
        )
        new_cursor = max(int(entry["cursor"]) for entry in batch)
        self.set_cursor(new_cursor)
        return {"processed": len(batch), "cursor": new_cursor, "page_id": page.id}

    @staticmethod
    def _compact_text(value: str, limit: int) -> str:
        value = re.sub(r"\s+", " ", value).strip()
        if len(value) <= limit:
            return value
        return value[: limit - 1].rstrip() + "…"

    def write_memory_bridge(self, *, limit: int = 8, link_limit: int = 8) -> Path:
        memory_dir = self.workspace / "memory"
        memory_dir.mkdir(parents=True, exist_ok=True)
        memory_path = memory_dir / "MEMORY.md"
        pages = self.list_pages(limit=limit)
        page_lines = (
            "\n".join(f"- [[{page.title}]] (`{page.id}`): {self._compact_text(page.content, 120)}" for page in pages)
            if pages
            else "- No Wiki pages yet."
        )
        links = self.list_links()
        recent_links = list(reversed(links[-max(1, link_limit):]))
        link_lines = (
            "\n".join(
                f"- [[{link.from_title}]] -{link.relation}-> [[{link.to_title}]]"
                for link in recent_links
            )
            if recent_links
            else "- No Wiki links yet."
        )
        block = (
            f"{BRIDGE_START}\n"
            "## LLM Wiki Memory\n\n"
            "Long-term memory is stored in `memory/wiki/` as Markdown pages and `links.jsonl`, "
            "plus a rebuildable SQLite index.\n"
            "Use `wiki_search` for broad recall and `wiki_read` for exact page context before relying on old facts.\n\n"
            "### Active Wiki Pages\n"
            f"{page_lines}\n"
            "\n### Recent Wiki Links\n"
            f"{link_lines}\n"
            f"{BRIDGE_END}"
        )
        existing = memory_path.read_text(encoding="utf-8") if memory_path.exists() else ""
        if BRIDGE_START in existing and BRIDGE_END in existing:
            start = existing.index(BRIDGE_START)
            end = existing.index(BRIDGE_END) + len(BRIDGE_END)
            updated = existing[:start].rstrip() + "\n\n" + block + "\n" + existing[end:].lstrip()
        else:
            updated = existing.rstrip() + "\n\n" + block + "\n" if existing.strip() else block + "\n"
        memory_path.write_text(updated, encoding="utf-8")
        return memory_path

    def remove_memory_bridge(self) -> bool:
        """Remove only the generated Wiki block from NanoBot's memory file."""
        memory_path = self.workspace / "memory" / "MEMORY.md"
        if not memory_path.is_file():
            return False

        existing = memory_path.read_text(encoding="utf-8")
        start = existing.find(BRIDGE_START)
        end = existing.find(BRIDGE_END, start + len(BRIDGE_START))
        if start < 0 or end < 0:
            return False

        end += len(BRIDGE_END)
        before = existing[:start].rstrip()
        after = existing[end:].lstrip()
        if before and after:
            updated = f"{before}\n\n{after}"
        elif before:
            updated = f"{before}\n"
        else:
            updated = after
        memory_path.write_text(updated, encoding="utf-8")
        return True

    def write_skill(self, *, force: bool = False) -> Path:
        skill_dir = self.workspace / "skills" / "llm-wiki"
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_path = skill_dir / "SKILL.md"
        if skill_path.exists() and not force:
            existing = skill_path.read_text(encoding="utf-8")
            if SKILL_MARKER not in existing:
                return skill_path
        skill_path.write_text(default_skill_markdown(), encoding="utf-8")
        return skill_path

    def remove_generated_skill(self) -> bool:
        """Remove the generated skill without touching a user-owned replacement."""
        skill_dir = self.workspace / "skills" / "llm-wiki"
        skill_path = skill_dir / "SKILL.md"
        if not skill_path.is_file():
            return False
        if SKILL_MARKER not in skill_path.read_text(encoding="utf-8"):
            return False

        skill_path.unlink()
        try:
            skill_dir.rmdir()
        except OSError:
            pass
        return True


def default_skill_markdown() -> str:
    return f"""---
name: llm-wiki
description: Use NanoBot LLM Wiki tools for durable long-term memory, project facts, user preferences, decisions, contradictions, and old context that may not fit in the current chat.
always: true
---

{SKILL_MARKER}

# LLM Wiki Memory

NanoBot has a local Wiki-backed long-term memory at `memory/wiki/`.

## When To Use

- Before answering questions that rely on old user preferences, long-running projects, prior decisions, or remembered facts.
- When the user asks to remember, forget, update, correct, or organize durable knowledge.
- When current context conflicts with remembered context; search first, then update the relevant page.

## Tools

- Use `wiki_search(query=...)` to find relevant pages.
- Use `wiki_read(selector=...)` before relying on details from a page.
- Use `wiki_upsert(title=..., content=..., mode="append")` to record durable facts.
- Use `wiki_link(from_selector=..., to_selector=...)` to connect related pages.
- Use `wiki_unlink(from_selector=..., to_selector=...)` to remove stale relationships.
- Use `wiki_import(path=...)` when the user asks to import a local folder or text knowledge base.
- Use `wiki_forget(selector=...)` when the user asks to delete a memory.
- Use `wiki_doctor()` when Wiki recall or installation health appears broken.

Do not treat the Wiki as infallible. Prefer recent user corrections, and update stale pages when the user gives better information.
"""
